{{- if le (int .Capabilities.KubeVersion.Minor) 24 }}
{{- if not .Values.global.podSecurityStandards.enforced }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.controller.name }}
    {{- include "azurefile.labels" . | nindent 4 }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities: []
  volumes:
    - 'emptyDir'
    - 'hostPath'
    - 'projected'
  hostNetwork: true
  hostIPC: false
  hostPID: false
  hostPorts:
    - min: {{ .Values.controller.livenessProbe.healthPort }}
      max: {{ .Values.controller.livenessProbe.healthPort }}
    - min: {{ .Values.controller.metricsPort }}
      max: {{ .Values.controller.metricsPort }}
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-{{ .Values.rbac.name }}-controller-psp
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ .Values.controller.name }}
    verbs:
      - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.rbac.name }}-controller-psp-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.controller }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-{{ .Values.rbac.name }}-controller-psp
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
