{{- if and .Values.provider (eq .Values.provider "capz") -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: af-premium
provisioner: file.csi.azure.com
mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
parameters:
  skuName: Premium_LRS
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: af-standard
provisioner: file.csi.azure.com
mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: af-premium-private
provisioner: file.csi.azure.com
mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
parameters:
  skuName: Premium_LRS
  networkEndpointType: "privateEndpoint"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: af-standard-private
provisioner: file.csi.azure.com
mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
  networkEndpointType: "privateEndpoint"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
{{- end }}
