apiVersion: v2
name: azurefile-csi-driver-app
description: A Helm chart to run Azure CSI driver for Azure File.
version: 0.0.1-dev
appVersion: 0.0.1-dev
home: https://github.com/giantswarm/azurefile-csi-driver-app
icon: https://s.giantswarm.io/app-icons/azure/1/dark.svg
annotations:
  application.giantswarm.io/team: phoenix
  config.giantswarm.io/version: 1.x.x
  ui.giantswarm.io/logo: https://s.giantswarm.io/app-icons/azure/1/dark.svg
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
  gpuInstances: false
  compatibleProviders: [azure]
